version: '3'
services:

  api:
    build: api/
    restart: unless-stopped
    networks:
    - bot
    depends_on: 
    - bot
    - mongo

  bot:
    build: bot/
    restart: unless-stopped
    networks:
    - bot

  mongo:
    image: 'mongo'
    restart: always
    volumes:
    - mongo:/var/lib/mongodb
    networks:
    - bot

volumes:
  mongo:

networks:
  bot:
    external: true
