version: '3'
services:

  api:
    build: .
    ports:
    - 16681:16681
    restart: unless-stopped
    networks:
    - bot

  bot:
    build: .
    ports: 16682:16682
    restart: unless-stopped
    networks:
    - bot

networks:
  integration:
    external: true
