version: '3'
services:

  api:
    build: api/
    restart: unless-stopped
    networks:
      main:
        aliases:
         - housebot
      housebot:
        aliases:
         - api
    depends_on: 
    - bot
    - mongo

  bot:
    build: bot/
    restart: unless-stopped
    networks:
      housebot:
        aliases:
          - bot

  mongo:
    image: 'mongo'
    restart: always
    volumes:
    - mongo:/var/lib/mongodb
    networks:
      housebot:
        aliases:
          - mongo


volumes:
  mongo:

networks:
  housebot:
    external: true
  main:
    external: true
