version: '3'
services:

  api:
    build: api/
    restart: unless-stopped
    ports:
    - 16681:16681
    networks:
    - housebot
    - main
    depends_on: 
    - bot
    - mongo

  bot:
    build: bot/
    restart: unless-stopped
    networks:
    - housebot
    - main

  mongo:
    image: 'mongo'
    restart: always
    volumes:
    - mongo:/var/lib/mongodb
    networks:
    - housebot

volumes:
  mongo:

networks:
  housebot:
    external: true
  main:
    external: true
