version: '3'
services:

  api:
    build: api/
    ports:
    - 16681:16681
    restart: unless-stopped
    networks:
    - bot
    depends_on: 
    - bot

  bot:
    build: bot/
    ports: 
    - 16682:16682
    restart: unless-stopped
    networks:
    - bot

networks:
  bot:
    external: true
